name: Continous integration for NepgroGo frontend
on:
  push:
    branches:
      - main 

jobs:
  build_hugo:
    name: Build hugo
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: theme-generator/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Gulp
        run: npm install gulp-cli -g

      - name: Install Node packages
        run: npm install
        working-directory: theme-generator

      - name: Gulp generate
        run: gulp dist
        working-directory: theme-generator
         
      - run: cp -a theme-generator/dist/assets/. static/

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      
      - name: Minify
        run: hugo --minify

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEPHROGO_F06FE }}'
          channelId: live
          projectId: nephrogo-f06fe
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
